services:
  - type: web
    name: backend-tecnicel
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      - key: SUPABASE_URL
        value: https://isszxxlrbbkjagkdssih.supabase.co
      - key: SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlzc3p4eGxyYmJramFna2Rzc2loIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQ0MjEwNDQsImV4cCI6MjA5OTk5NzA0NH0.6qZhTDT8QWyRpmf-f1nQz-VY-ETZybt0JgdmFEJd4Rw
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: SUPABASE_STORAGE_BUCKET
        value: estado-dispositivos
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 1h
      - key: JWT_REFRESH_EXPIRES_IN
        value: 7d
