import { Router } from 'express';
import { authRoutes } from './auth.routes';
import { usuariosRoutes, rolesRoutes, permisosRoutes } from './usuarios.routes';
import { clientesRoutes, direccionesRoutes } from './clientes.routes';
import { marcasRoutes } from './marcas.routes';
import { modelosRoutes, marcasModelosRoutes } from './modelos.routes';
import { dispositivosRoutes } from './dispositivos.routes';
import { categoriasServicioRoutes } from './categorias-servicio.routes';
import { serviciosRoutes } from './servicios.routes';
import { serviciosModelosRoutes } from './servicios-modelos.routes';
import { solicitudesRoutes } from './solicitudes.routes';
import { solicitudesAdminRoutes } from './solicitudes-admin.routes';
import { diagnosticosRoutes } from './diagnosticos.routes';
import { cotizacionesRoutes } from './cotizaciones.routes';
import { reparacionesRoutes } from './reparaciones.routes';
import { productosRoutes } from './productos.routes';
import { inventarioRoutes } from './inventario.routes';
import { tecnicosRoutes } from './tecnicos.routes';
import { transportesRoutes } from './transportes.routes';
import { sucursalesRoutes } from './sucursales.routes';
import { pagosRoutes } from './pagos.routes';
import { notificacionesRoutes } from './notificaciones.routes';
import { calificacionesRoutes } from './calificaciones.routes';
import { dashboardRoutes } from './dashboard.routes';
import { estadoDispositivoRoutes } from './estado-dispositivo.routes';
import { uploadRoutes } from './upload.routes';
import { ticketRoutes } from './ticket.routes';

const router = Router();

router.use('/auth', authRoutes);
router.use('/usuarios', usuariosRoutes);
router.use('/roles', rolesRoutes);
router.use('/permisos', permisosRoutes);
router.use('/clientes', clientesRoutes);
router.use('/direcciones', direccionesRoutes);
router.use('/marcas', marcasRoutes);
router.use('/modelos', modelosRoutes);
router.use('/marcas', marcasModelosRoutes);
router.use('/mis-dispositivos', dispositivosRoutes);
router.use('/categorias-servicio', categoriasServicioRoutes);
router.use('/servicios', serviciosRoutes);
router.use('/servicios-modelos', serviciosModelosRoutes);
router.use('/modelos', serviciosRoutes);
router.use('/solicitudes', solicitudesAdminRoutes);
router.use('/mis-solicitudes', solicitudesRoutes);
router.use('/solicitudes', diagnosticosRoutes);
router.use('/solicitudes', cotizacionesRoutes);
router.use('/cotizaciones', cotizacionesRoutes);
router.use('/diagnosticos', diagnosticosRoutes);
router.use('/reparaciones', reparacionesRoutes);
router.use('/productos', productosRoutes);
router.use('/inventario', inventarioRoutes);
router.use('/tecnicos', tecnicosRoutes);
router.use('/tecnico', tecnicosRoutes);
router.use('/transportes', transportesRoutes);
router.use('/solicitudes', transportesRoutes);
router.use('/sucursales', sucursalesRoutes);
router.use('/pagos', pagosRoutes);
router.use('/mis-pagos', pagosRoutes);
router.use('/notificaciones', notificacionesRoutes);
router.use('/calificaciones', calificacionesRoutes);
router.use('/solicitudes', calificacionesRoutes);
router.use('/reclamos', calificacionesRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/reportes', dashboardRoutes);
router.use('/solicitudes', estadoDispositivoRoutes);
router.use('/upload', uploadRoutes);
router.use('/solicitudes', ticketRoutes);

export { router as routes };
